import { PRIORITY, STATUS } from '../constants/contants';

export const TASKS = [
  {
    id: 1,
    title: 'task 1',
    description: 'testing the 1 tasks',
    priorityLevel: PRIORITY[0],
    status: STATUS[0],
    dueDate: new Date('02-11-2024'),
  },
  {
    id: 2,
    title: 'task 2',
    description: 'testing the 2 tasks',
    priorityLevel: PRIORITY[1],
    status: STATUS[0],
    dueDate: new Date('02-12-2024'),
  },
  {
    id: 3,
    title: 'task 3',
    description: 'testing the 3 tasks',
    priorityLevel: PRIORITY[2],
    status: STATUS[1],
    dueDate: new Date('02-13-2024'),
  },
  {
    id: 4,
    title: 'task 4',
    description: 'testing the 4 tasks',
    priorityLevel: PRIORITY[3],
    status: STATUS[1],
    dueDate: new Date('02-14-2024'),
  },
  {
    id: 5,
    title: 'task 5',
    description: 'testing the 5 tasks',
    priorityLevel: PRIORITY[0],
    status: STATUS[2],
    dueDate: new Date('02-15-2024'),
  },
  {
    id: 6,
    title: 'task 6',
    description: 'testing the 6 tasks',
    priorityLevel: PRIORITY[1],
    status: STATUS[2],
    dueDate: new Date('02-16-2024'),
  },
  {
    id: 7,
    title: 'task 7',
    description: 'testing the 7 tasks',
    priorityLevel: PRIORITY[2],
    status: STATUS[3],
    dueDate: new Date('02-17-2024'),
  },
  {
    id: 8,
    title: 'task 8',
    description: 'testing the 8 tasks',
    priorityLevel: PRIORITY[3],
    status: STATUS[3],
    dueDate: new Date('02-18-2024'),
  },
];
